In [24]:
#q1
import pandas as pd


data = {
    'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Refund': ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Divorced',
                       'Married', 'Divorced','Single', 'Married', 'Single'],
    'Taxable Income': ['125K', '100K', '70K', '120K', '95K', '60K',
                       '220K', '85K', '75K', '90K'],
    'Cheat': ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
}


df = pd.DataFrame(data)


print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7     No       Divorced           220K    No
7    8    Yes         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [25]:
#q2
 print(df.loc[0])
print(df.loc[4])
print(df.loc[7])
print(df.loc[8])

Tid                    1
Refund               Yes
Marital Status    Single
Taxable Income      125K
Cheat                 No
Name: 0, dtype: object
Tid                      5
Refund                  No
Marital Status    Divorced
Taxable Income         95K
Cheat                  Yes
Name: 4, dtype: object
Tid                    8
Refund               Yes
Marital Status    Single
Taxable Income       85K
Cheat                Yes
Name: 7, dtype: object
Tid                     9
Refund                 No
Marital Status    Married
Taxable Income        75K
Cheat                  No
Name: 8, dtype: object

In [26]:
#q3(1)
df.iloc[3:7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7     No       Divorced           220K    No

In [27]:
#q3(2)
df.iloc[4:8,2:4]

  Marital Status Taxable Income
4       Divorced            95K
5        Married            60K
6       Divorced           220K
7         Single            85K

In [28]:
#q3(3)
df.iloc[1:4]

   Tid Refund Marital Status Taxable Income Cheat
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No

In [37]:





from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv

In [38]:
#q4
import pandas as pd

df = pd.read_csv("Iris.csv")
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [61]:
#q5
import pandas as pd


df = pd.read_csv("Iris.csv")


df = df.drop(index=3)


df = df.drop(df.columns[2], axis=1)


print(df)

      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
0      1            5.1            1.4           0.2     Iris-setosa
1      2            4.9            1.4           0.2     Iris-setosa
2      3            4.7            1.3           0.2     Iris-setosa
4      5            5.0            1.4           0.2     Iris-setosa
5      6            5.4            1.7           0.4     Iris-setosa
..   ...            ...            ...           ...             ...
145  146            6.7            5.2           2.3  Iris-virginica
146  147            6.3            5.0           1.9  Iris-virginica
147  148            6.5            5.2           2.0  Iris-virginica
148  149            6.2            5.4           2.3  Iris-virginica
149  150            5.9            5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [62]:
#q6
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [63]:
#q6(a)
print("Shape of the DataFrame:", df.shape)

Shape of the DataFrame: (5, 10)

In [64]:
#q6(b)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [65]:
#q6(c)
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [66]:
#q6(d)
print(df.head())
print(df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [72]:
#q6(e)
import pandas as pd

# i.
average_salary = df['Salary'].mean()

# ii.
total_bonus = df['Bonus'].sum()

# iii.
youngest_age = df['Age'].min()

# iv.
highest_performance_rating = df['Rating'].max()


print("Average Salary:" ,average_salary)
print("Total Bonus Paid:" ,total_bonus)
print("Youngest Employee's Age:", youngest_age)
print("Highest Performance Rating:",highest_performance_rating)

Average Salary: 60000.0
Total Bonus Paid: 27500
Youngest Employee's Age: 28
Highest Performance Rating: 4.7

In [75]:
 #q6(f)
 df=df.sort_values(by='Salary', ascending=False)
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [79]:
#q6(g)
def categorize_performance(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'


df['performance_category'] =df['Rating'].apply(categorize_performance)
print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating performance_category
1   2017-07-19    Male   7000     4.0                 Good
2   2013-06-01    Male   6000     3.8              Average
4   2010-11-25    Male   5000     3.5              Average
3   2021-02-10  Female   4500     4.7            Excellent
0   2020-03-15  Female   5000     4.5            Excellent

In [80]:
#q6(h)
missing_values = df.isnull().sum()


print(missing_values)

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
performance_category    0
dtype: int64

In [81]:
#q6(i)
df.rename(columns={'Employee_ID': 'ID'}, inplace=True)


print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
3  104    Diana  Marketing   28   55000                    3   2021-02-10
0  101    Alice         HR   29   50000                    4   2020-03-15

   Gender  Bonus  Rating performance_category
1    Male   7000     4.0                 Good
2    Male   6000     3.8              Average
4    Male   5000     3.5              Average
3  Female   4500     4.7            Excellent
0  Female   5000     4.5            Excellent

In [87]:
#q6(j)
find_employees = df[(df['Years_of_Experience'] > 5) & (df['Department'] == 'IT')]


print(find_employees)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating performance_category     Tax
1   Male   7000     4.0                 Good  7000.0
2   Male   6000     3.8              Average  6500.0

In [85]:
#q6(k)
df['Tax'] = df['Salary'] * 0.10
print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25
3  104    Diana  Marketing   28   55000                    3   2021-02-10
0  101    Alice         HR   29   50000                    4   2020-03-15

   Gender  Bonus  Rating performance_category     Tax
1    Male   7000     4.0                 Good  7000.0
2    Male   6000     3.8              Average  6500.0
4    Male   5000     3.5              Average  6000.0
3  Female   4500     4.7            Excellent  5500.0
0  Female   5000     4.5            Excellent  5000.0

In [86]:
#q6(l)
df.to_csv('modified_employees.csv', index=False)